<LayoutWindow>:
    BoxLayout:
        BoxLayout:
            orientation: "vertical"
            padding: 20, 20, 0, 20
            spacing: 20
            Button:
            Button:
            Button:
            Button:

    BoxLayout:
        BoxLayout:
            padding: 20, 20, 20, 20
            spacing: 20
            Button:
            Button:
            Button:
            Button:
            Button:
